name: example1
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ^2.1.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  logging: ^1.0.2
  json_serializable: ^6.1.0
  yaml: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.19.0
  args: ^2.3.0
  sqflite: ^2.0.2
  path: ^1.8.0


flutter:
  uses-material-design: true
  assets:
    - workflow/
    - history/
