name: build-web

on:
  push:
    branches: [master]

jobs:
  build-web:
    name: flutter build and deploy website
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: subosito/flutter-action@v1
      with:
        channel: dev
    - name: config
      run: flutter config --enable-web
    - name: doctor
      run: flutter doctor
    - name: devices
      run: flutter devices
    - name: pub get
      run: flutter pub get
    #- name: test
    #  run: flutter test
    - name: build web
      run: flutter build web
    - name: fix urlencode
      run: |
        set -x
        sudo -E apt install -y -qq gridsite-clients
        for i in build/web/assets/workflow/*.yaml ; do
          n=$(urlencode -d $i)
          [ "$n" != "$i" ] && mv $i $n || true
        done
      env:
        DEBIAN_FRONTEND: noninteractive
    - name: list resource
      run: ls -lR build/web
    - name: disable jekyll
      run: touch build/web/.nojekyll
    - name: deploy gh-pages
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./build/web
